version: '3.6'
services:
  tweeps_test:
    image: 04091984/tweeps_test
    
    depends_on:
      - memcached
      - redis
      - sidekiq

  redis:
    image: 'redis:5.0.8-alpine'

  sidekiq:
    depends_on:
      - 'redis'
  
  memcached:
    image: 'memcached'