default: &default
  adapter: postgresql
  encoding: unicode
  host: pg
  username: <%= ENV['PG_USR'] %>
  password: <%= ENV['PG_PWD'] %>
  pool: <%= ENV.fetch("DB_POOL") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: tweeps_development

test:
  <<: *default
  database: tweeps_test

production:
  <<: *default
  database: tweeps_production
  username: myapp
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>
